In [178]:
import numpy as np

In [179]:
np.__version__

'2.3.1'

## Create & Read

In [180]:
arr1 = np.array([1,2,3,4,5,6])

In [181]:
arr1

array([1, 2, 3, 4, 5, 6])

In [182]:
type(arr1)

numpy.ndarray

In [183]:
arr1.shape

(6,)

In [184]:
arr1.dtype

dtype('int64')

In [185]:
arr1.ndim

1

In [186]:
arr1.size

6

In [187]:
arr2 = np.array([[1,4,5],[6,7,4]])

In [188]:
arr2

array([[1, 4, 5],
       [6, 7, 4]])

In [189]:
arr2.shape # (row, col)

(2, 3)

In [190]:
arr2.dtype

dtype('int64')

In [191]:
arr2.ndim

2

In [192]:
arr2.size

6

#### 3D Array

In [193]:
arr3 = np.array([[[1,4,5],[6,7,4]],[[3,5,4],[5,8,7]],[[1,4,5],[6,7,4]]])

In [194]:
arr3

array([[[1, 4, 5],
        [6, 7, 4]],

       [[3, 5, 4],
        [5, 8, 7]],

       [[1, 4, 5],
        [6, 7, 4]]])

In [195]:
arr3.ndim

3

In [196]:
arr3.shape

(3, 2, 3)

#### Create random array

In [197]:
randomArr = np.random.rand(3,2,3)

In [198]:
randomArr

array([[[0.32479303, 0.83570573, 0.78835059],
        [0.02185034, 0.52184692, 0.63693417]],

       [[0.53677104, 0.48818115, 0.00419811],
        [0.0464514 , 0.21068171, 0.92933665]],

       [[0.10420127, 0.13453233, 0.36265144],
        [0.19048945, 0.19750443, 0.01527238]]])

In [199]:
randomArr.dtype

dtype('float64')

In [200]:
zeros = np.zeros((3,2,3))

In [201]:
zeros

array([[[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]]])

In [202]:
zeros.ndim

3

In [203]:
full = np.full((3,2,3),8)

In [204]:
full

array([[[8, 8, 8],
        [8, 8, 8]],

       [[8, 8, 8],
        [8, 8, 8]],

       [[8, 8, 8],
        [8, 8, 8]]])

In [205]:
ones = np.ones((3,2,3))

In [206]:
ones

array([[[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]]])

In [207]:
arr3

array([[[1, 4, 5],
        [6, 7, 4]],

       [[3, 5, 4],
        [5, 8, 7]],

       [[1, 4, 5],
        [6, 7, 4]]])

In [208]:
arr3[0]

array([[1, 4, 5],
       [6, 7, 4]])

In [209]:
arr3[0][0][0]

np.int64(1)

In [210]:
arr3[0:2]

array([[[1, 4, 5],
        [6, 7, 4]],

       [[3, 5, 4],
        [5, 8, 7]]])

In [211]:
arr3[-1]

array([[1, 4, 5],
       [6, 7, 4]])

In [212]:
arr3[1][0][1]

np.int64(5)

### Create random array

In [213]:
randomArr = np.random.rand(3, 2, 3)
randomArr

array([[[0.64024365, 0.17295874, 0.60241954],
        [0.23665877, 0.25373204, 0.72836393]],

       [[0.346379  , 0.49726281, 0.13050243],
        [0.20390495, 0.62017348, 0.56242728]],

       [[0.94425309, 0.24621433, 0.04170324],
        [0.12417759, 0.75610906, 0.38941408]]])

In [214]:
randomArr.dtype

dtype('float64')

### Update & Delete

In [215]:
a1 = np.random.rand(2,3,2)
a2 = np.random.rand(2,3,2)

In [216]:
a1

array([[[0.39891099, 0.19526464],
        [0.93264762, 0.1985802 ],
        [0.16677616, 0.19660434]],

       [[0.17741139, 0.87746733],
        [0.80341472, 0.67433683],
        [0.90125138, 0.65442845]]])

In [217]:
a2

array([[[0.91453543, 0.9719218 ],
        [0.19282482, 0.87673181],
        [0.89857901, 0.88290444]],

       [[0.25581682, 0.3721724 ],
        [0.37053293, 0.60698497],
        [0.9035099 , 0.48489377]]])

### Basic Math Operations

In [218]:
np.add(a1,a2)

array([[[1.31344643, 1.16718644],
        [1.12547244, 1.07531201],
        [1.06535517, 1.07950877]],

       [[0.43322821, 1.24963972],
        [1.17394764, 1.2813218 ],
        [1.80476128, 1.13932222]]])

In [219]:
np.subtract(a1,a2)

array([[[-0.51562444, -0.77665717],
        [ 0.7398228 , -0.6781516 ],
        [-0.73180285, -0.6863001 ]],

       [[-0.07840542,  0.50529493],
        [ 0.43288179,  0.06735186],
        [-0.00225852,  0.16953468]]])

In [220]:
np.divide(a1,a2)

array([[[0.43618976, 0.20090571],
        [4.83676131, 0.22650051],
        [0.18559989, 0.22267907]],

       [[0.6935095 , 2.35769051],
        [2.16826809, 1.11096134],
        [0.99750028, 1.34963262]]])

In [221]:
np.multiply(a1,a2)

array([[[0.36481824, 0.18978196],
        [0.17983761, 0.17410158],
        [0.14986156, 0.17358284]],

       [[0.04538482, 0.32656912],
        [0.29769161, 0.40931232],
        [0.81428955, 0.31732828]]])

In [222]:
sqrt = np.sqrt(25)
abs = np.abs(-2)
power = np.power(2,8)
log = np. log(25)
mins = np.min(a1)
maxs = np.max(a2)

In [223]:
sqrt

np.float64(5.0)

In [224]:
abs

np.int64(2)

In [225]:
power

np.int64(256)

In [226]:
log

np.float64(3.2188758248682006)

In [227]:
mins

np.float64(0.1667761627018216)

In [228]:
maxs

np.float64(0.97192180363423)

### Update

In [229]:
arr3

array([[[1, 4, 5],
        [6, 7, 4]],

       [[3, 5, 4],
        [5, 8, 7]],

       [[1, 4, 5],
        [6, 7, 4]]])

In [230]:
arr3[0,0,2] = 500
arr3

array([[[  1,   4, 500],
        [  6,   7,   4]],

       [[  3,   5,   4],
        [  5,   8,   7]],

       [[  1,   4,   5],
        [  6,   7,   4]]])

In [231]:
arr3.sort()
arr3

array([[[  1,   4, 500],
        [  4,   6,   7]],

       [[  3,   4,   5],
        [  5,   7,   8]],

       [[  1,   4,   5],
        [  4,   6,   7]]])

In [232]:
# Reshape
arr3.shape

(3, 2, 3)

In [233]:
arr3_reshape = arr3.reshape((2,3,3))
arr3_reshape

array([[[  1,   4, 500],
        [  4,   6,   7],
        [  3,   4,   5]],

       [[  5,   7,   8],
        [  1,   4,   5],
        [  4,   6,   7]]])

#### Appending & Inserting

In [234]:
zeroes = np.zeros((3,2,3))

In [235]:
zeroes 

array([[[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]]])

In [236]:
# Create a new array
new_array = np.ones((3,2,3))
new_array

array([[[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]]])

In [237]:
appd = np.append(zeroes, new_array,axis=0) # axis 0 = row, axis 1 = coulm
appd

array([[[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]]])

In [238]:
# Insert 

In [239]:
zeroes

array([[[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]]])

In [240]:
new_array

array([[[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]]])

In [241]:
inserted_array = np.insert(zeroes, 1, new_array, axis=0)

In [242]:
inserted_array

array([[[0., 0., 0.],
        [0., 0., 0.]],

       [[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]]])

### Delete

In [243]:
arr4 = np.random.rand(3,2,3)
arr4

array([[[0.84325428, 0.9959071 , 0.01976154],
        [0.31917442, 0.03753614, 0.02169414]],

       [[0.04436386, 0.50585625, 0.98387242],
        [0.94520621, 0.65930755, 0.09646642]],

       [[0.8929239 , 0.15070852, 0.58354055],
        [0.71318022, 0.01695865, 0.31159213]]])

In [245]:
# delete the array
arr5=np.delete(arr4,0,axis=1)

In [246]:
arr5

array([[[0.31917442, 0.03753614, 0.02169414]],

       [[0.94520621, 0.65930755, 0.09646642]],

       [[0.71318022, 0.01695865, 0.31159213]]])

In [247]:
np.save("new_array",arr5)

In [249]:
np.load("new_array.npy")

array([[[0.31917442, 0.03753614, 0.02169414]],

       [[0.94520621, 0.65930755, 0.09646642]],

       [[0.71318022, 0.01695865, 0.31159213]]])